### ISSUE TITLE
Checkout Functionality

### ISSUE THREAD

**Issue by mabonmn** [EECE3093C/team-project-nontoastermakers#53]
Create the checkout page and provide the user the opttion to confirm the order and write to a database.

**Comment by nimmoev** [comment]
To complete this,  I need to move Menu's pathing to my cart.py file.  This requires menu to not be called from view1.home.  I need to fix home.html to set view1.home pathing to home.html rather than menu.html.  Requesting permission to do this in this branch even though it is not in the scope of this issue.

**Comment by mabonmn** [comment]
Approved @nimmoev

**Comment by nimmoev** [comment]
I have moved menu.html pathing to cart.py. home.html is now called from views1.py after login.  menu.html is now called from cart.py.  home.html had to be modified to allow execution without error.  These changes will effect Fawwaaz's tasks, so I recommend his changes be built directly from this change.

**Comment by nimmoev** [comment]
Forgot to move this issue to in progress, has been in progress since 4/1.  Waiting on Issue #60 to progress.

**Comment by nimmoev** [comment]
Complete, need changes tested before merge with main.
